<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="9" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="56350" started-at="2017-02-10T08:48:11Z" finished-at="2017-02-10T08:49:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="56350" started-at="2017-02-10T08:48:11Z" finished-at="2017-02-10T08:49:08Z">
      <class name="core.SignUpPageTest">
        <test-method status="PASS" signature="test_01_verify_content_quotes()[pri:0, instance:core.SignUpPageTest@4f7d0008]" name="test_01_verify_content_quotes" duration-ms="5250" started-at="2017-02-10T00:48:12Z" finished-at="2017-02-10T00:48:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_01_verify_content_quotes -->
        <test-method status="PASS" signature="test_02_verify_content_current_city()[pri:0, instance:core.SignUpPageTest@4f7d0008]" name="test_02_verify_content_current_city" duration-ms="4327" started-at="2017-02-10T00:48:17Z" finished-at="2017-02-10T00:48:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_02_verify_content_current_city -->
        <test-method status="PASS" signature="test_03_verify_content_current_weather()[pri:0, instance:core.SignUpPageTest@4f7d0008]" name="test_03_verify_content_current_weather" duration-ms="4338" started-at="2017-02-10T00:48:21Z" finished-at="2017-02-10T00:48:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_03_verify_content_current_weather -->
        <test-method status="FAIL" signature="test_04_verify_content_date()[pri:0, instance:core.SignUpPageTest@4f7d0008]" name="test_04_verify_content_date" duration-ms="4348" started-at="2017-02-10T00:48:25Z" finished-at="2017-02-10T00:48:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [February 9, 2017 ] but found [February 10, 2017 ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [February 9, 2017 ] but found [February 10, 2017 ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at core.SignUpPageTest.test_04_verify_content_date(SignUpPageTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_04_verify_content_date -->
        <test-method status="PASS" signature="test_05_verify_content_os()[pri:0, instance:core.SignUpPageTest@4f7d0008]" name="test_05_verify_content_os" duration-ms="4324" started-at="2017-02-10T00:48:30Z" finished-at="2017-02-10T00:48:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_05_verify_content_os -->
        <test-method status="FAIL" signature="test_07_verify_link_facebook()[pri:0, instance:core.SignUpPageTest@4f7d0008]" name="test_07_verify_link_facebook" duration-ms="7721" started-at="2017-02-10T00:48:34Z" finished-at="2017-02-10T00:48:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to Facebook - Log In, Sign Up or Learn More] but found [Facebook - Log In or Sign Up]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to Facebook - Log In, Sign Up or Learn More] but found [Facebook - Log In or Sign Up]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at core.SignUpPageTest.test_07_verify_link_facebook(SignUpPageTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_07_verify_link_facebook -->
        <test-method status="FAIL" signature="test_08_verify_link_twitter()[pri:0, instance:core.SignUpPageTest@4f7d0008]" name="test_08_verify_link_twitter" duration-ms="8829" started-at="2017-02-10T00:48:42Z" finished-at="2017-02-10T00:48:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Twitter] but found [Twitter. It's what's happening.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Twitter] but found [Twitter. It's what's happening.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at core.SignUpPageTest.test_08_verify_link_twitter(SignUpPageTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_08_verify_link_twitter -->
        <test-method status="PASS" signature="test_09_verify_link_flick()[pri:0, instance:core.SignUpPageTest@4f7d0008]" name="test_09_verify_link_flick" duration-ms="8199" started-at="2017-02-10T00:48:51Z" finished-at="2017-02-10T00:48:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_09_verify_link_flick -->
        <test-method status="PASS" signature="test_10_verify_link_youtube()[pri:0, instance:core.SignUpPageTest@4f7d0008]" name="test_10_verify_link_youtube" duration-ms="8964" started-at="2017-02-10T00:48:59Z" finished-at="2017-02-10T00:49:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_10_verify_link_youtube -->
      </class> <!-- core.SignUpPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
